name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pguser
          POSTGRES_DB: study_on_billing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, zip
          coverage: pcov
          tools: composer

      - name: Configure environment
        run: |
          echo "DATABASE_URL=pgsql://pguser:pguser@postgres:5432/study_on_billing" > .env.test
          echo "APP_ENV=test" >> .env.test
          echo "JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem" >> .env.test
          echo "JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem" >> .env.test
          echo "JWT_PASSPHRASE=study" >> .env.test

      - name: Generate JWT keys
        run: |
          mkdir -p config/jwt
          openssl genrsa -out config/jwt/private.pem 2048
          openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h postgres -U pguser -d postgres && break
            sleep 2
            [ $i -eq 10 ] && exit 1
          done

      - name: Initialize database
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate -n --env=test || php bin/console doctrine:schema:update --force --env=test
          php bin/console doctrine:fixtures:load -n --env=test

      - name: Run tests
        run: php bin/phpunit
